language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: E/BSS8OyKUZ1HAtxZYGfzCnVLkcbLtGhtntfRk8AV9aGSS4Dunun/4IlBILPFg6/P35wBEJhDObiQA9GlkuPjn2VUoqdTZZGMSPRT8YOKbmt2ZzT5Ws9HABT2bTjQCUN/XPh+Q1qsAFB8gYTIvoVoiuqkmXZebzQnr6WJ15dbAxbZbkEmqc/2dJ53FM8/F694xUlwUHBlPf9FGk8JsdgPQSVQicXm8Jljo6Sva1x5jIO1+gGh2y4J4ZJup5J0Ye1cB5SY/JbMLU75mPrKIYCqq6aijDgYiY2u9vaNECXG0zL4u2vXsMOIeNFWkPmK8vRjLXAt2Ii4jLJ1Z2mN/RD7NCt0VQ+KLzrr1NXguJGovuK61rIhB4zqASmEgaag9oBBQuhpZ9RdntlT2SZz/ZXngzc+PipvveuVck0ALNu/jkKdOczUplHcXkotMCNMLve4ZLnQgV/PtBE8FV41uLZeYKge68TZmZnckaeRfRjdBcnebyh5AQFtzKg9LWCrFg1gdALHFOqKOC1re8baB3eDW9zsjcFui1A0UMG4k4oqhdLgFgd8BFDJzI3903WyTuS9/0CIxzH5jPdPmtEoTjSXHxRfP5qRqj1Qz90NiRoD5R81OwINGY9oWDi8alaDa6q5PuL3lSwTzX+nAAjaQ+6uYGg7E/ZXMoAUK7pcW/8gNs=
  app: serene-falls-45294
  on:
    repo: Thinkful-Ed/node-restaurants-app-mongoose
